### ISSUE TITLE
Upload and Choose Image button are somewhat confusing

### ISSUE THREAD

**Issue by LeoKwo** [Plant-Pharmacy/Main#15]
Since the upload button is not activated until one image is selected, why not make the upload button appear after the image is uploaded. Initially, I pressed on both buttons to realize only one of them is supposed to be working.

**Comment by 3ickey** [comment]
Addressed by commit 51be7d8 to make the buttons less confusing but the user flow stayed the same as making the submit button appear on file selection is an extra step the user would have to take.
