### ISSUE TITLE
[major] Image not shown after uploaded

### ISSUE THREAD

**Issue by Aimee0103wu** [Plant-Pharmacy/Main#21]
**Describe the bug**
After uploading an image that is clearly within the size limitation (the image I uploaded is 2.3MB), my image did not show up even though there is a prediction provided.

**To Reproduce**
1. Click on Choose Image
2. Select an image with a bigger size (mine is 2.3MB)
3. Submit the image.
4. see error: my selected image is not shown yet a prediction is provided.

**Expected behavior**
I expect my uploaded image to appear alongside the prediction for the plant.

**Screenshot**
<img width="1440" alt="Screen Shot 2019-12-05 at 8 32 53 PM" src="https://user-images.githubusercontent.com/46922678/70296171-739a8700-179e-11ea-9a69-9f779af1e17e.png">
<img width="1440" alt="Screen Shot 2019-12-05 at 8 32 39 PM" src="https://user-images.githubusercontent.com/46922678/70296172-74331d80-179e-11ea-8631-c634c685f4db.png">

**Desktop**

- Mac book pro
- chrome

**Comment by 3ickey** [comment]
Not fixed. This is caused by huge image dimensions. We did not want to set a fixed image dimension because we think it limits users.
