### ISSUE TITLE
[MAJOR] No loading feedback or page redirection when submitting photo

### ISSUE THREAD

**Issue by tfpenner** [Plant-Pharmacy/Main#23]
Describe the bug
There is no visual indication of a successful upload of an image or any indication of where to look for results after a photo is submitted

To Reproduce
Choose a photo to upload and click submit.

Expected behavior
User is given visual feedback that shows the photo was successfully submitted, and the user is directed to the bottom of the page where the results are.

Browser:
Chrome (Desktop)

**Comment by 3ickey** [comment]
There is an upload loading indicator on the top of the page. We have made it more visible and the user is now directed to the result section after the submit button has been clicked. Addressed by commit 51be7d8
