### ISSUE TITLE
[Minor] Plant Report gets Wiped after Uploading

### ISSUE THREAD

**Issue by CD6-timury** [Plant-Pharmacy/Main#24]
**Describe the bug**
If you've already reviewed a plant report & would like to test another picture - you choose to upload a new image, and as soon as you select your file - your previous report gets wiped (it goes to the default image & "... prediction is shown here")

**To Reproduce**
1. Choose an image to upload
2. Click submit
3. Choose an image to upload

**Expected behavior**
The previous report should get wiped only after you click "Submit" button.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise (1803)
 - Browser (Version 78.0.3904.108 64 Bit)

**Comment by 3ickey** [comment]
Addressed by commit 51be7d8. Previous results stay intact until a new upload is initiated.
