### ISSUE TITLE
[Major] All the information about the plant is wrong.

### ISSUE THREAD

**Issue by tran6388-1672747** [Plant-Pharmacy/Main#25]
**Description:**
I hate to write major issue; but, I think your app does not work at all because it give all the wrong information back to the user. As you can see, i pick like 5 to 10 plant with a certain disease (images are download online). But, all the app does is give me back wrong disease information for the plant. I thought the whole purpose of your app is to give a prediction about the disease for plant. I understand that this is really really difficult to implement, I don't even know how to do this. But, I expect to have at least one correct out of 10 plants try. But, I got none are correct. So, I think your app fail in its mission as information provider. So, I have to say this is a major defect.

**To Reproduce**

1. Go to "https://secure-tundra-64652.herokuapp.com/"
2. Click on choose and image. And add an image from the file.
3. click on Submit.
4. See error: The information is wrong about the plants.

**Expected behavior**
Give the correct disease info about the plant.

**Screenshots**

![Screenshot (67)](https://user-images.githubusercontent.com/23422230/70341303-82695400-1807-11ea-99a5-9d48fb4d3254.png)

![Screenshot (65)](https://user-images.githubusercontent.com/23422230/70341316-87c69e80-1807-11ea-9019-50168d6c90a1.png)

**Comment by Kyrabautista** [comment]
Hi! Thanks for the bug report. 
Yes, you are correct. We are well aware that this was an ambitious project with its own sets of challenges. Unfortunately, the PlantAI model we relied on to classify plant diseases is not something we have control over. Also, we'd like to convey that model accuracy is not a measurement of our mission's success. Predictions are subject to change and improve over time.
