### ISSUE TITLE
[Minor] No visual feedback

### ISSUE THREAD

**Issue by xCyziw** [Plant-Pharmacy/Main#26]
_Note: don't forget to create issue templates for major and minor issues_

**The issue**

When I upload an image, there's no feedback indicating that the image has been uploaded. When I press the submit button after uploading an image, there is no visual feedback that the image has been submitted, or that the plant report is ready.

**Reproduction steps**

1. Click "Choose Image" button
2. Select an image from computer to upload
3. Click "Submit" button

**Why it's problematic**

There's no way to know when the image has been upload, and when the form can be submitted. The plant report shows up below the image selector, so users have to scroll down to see the results.

**Suggestions**

- Include a confirmation message once an image has been uploaded
- Make the submit button a different color/visual treatment from the "Choose Image" button
- Include some sort of feedback once the uploaded image has been submitted (e.g., automatically scroll the page to the plant report, or show a message saying the form has been submitted and that the plant report can be viewed below)

**Screenshot**

I've uploaded & submitted the form, but there's no feedback. I have to scroll the page myself to be able to see the plant report:

![image](https://user-images.githubusercontent.com/14927028/70356834-3085f580-182a-11ea-9f1e-81aeb04a914d.png)

**Comment by 3ickey** [comment]
Addressed by commit 51be7d8 and 2e7c310
