### ISSUE TITLE
[minor] still no visual feedback

### ISSUE THREAD

**Issue by anthonyqcn** [Plant-Pharmacy/Main#28]
**Describe the bug**
There's no way to know that I've uploaded a photo, and there's no signifier to tell me to scroll down after pressing submit to see the plant report, which can seriously deter users from using the product when they think it's not working even if it actually is.

**To Reproduce**

- Go to 'https://secure-tundra-64652.herokuapp.com/'
- Click on 'Choose image'
- Upload photo found here: https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjXs-aPkKjmAhWyKn0KHdUdA6QQjRx6BAgBEAQ&url=https%3A%2F%2Fdissolve.com%2Fstock-photo%2FAgriculture-Crop-Disease-Anthracnose-tomato-royalty-free-image%2F101-D869-29-187&psig=AOvVaw1cDgPzDaBem8A9Uk0TcZW9&ust=1575965765540093
- Error occurs here: no indicator that a photo has been uploaded
- Press submit button
- Error occurs here: loading occurs but then no indicator at all that the results are displayed below the submit

**Expected behavior**
Expect an indicator that a photo is uploaded and ready to be submitted, as well as an indicator that you have to scroll down to see the report.

**Comment by 3ickey** [comment]
Addressed by commit 51be7d8
