### ISSUE TITLE
Minor - Inaccurate Information being displayed

### ISSUE THREAD

**Issue by chencal-1622780** [Plant-Pharmacy/Main#30]
Describe the minor issue
Information seems to be inaccurate in terms of inaccurate information regarding the picture. I submitted a picture of my dog and said it was a tomato...

To Reproduce

1. Click on submit an image
2. Choose a picture that is not a plant
3. Information will be information on a plant

Screenshots:
<img width="1192" alt="Screen Shot 2019-12-09 at 5 55 51 AM" src="https://user-images.githubusercontent.com/26780640/70441137-9f409a00-1a48-11ea-8a71-239f5ef5295a.png">

**Comment by 3ickey** [comment]
Duplicated issue addressed in issue #25
